import  Header  from "@/components/Header"
import  Footer  from "@/components/Footer"

import '../../public/styles/shared/global.css'

export const metadata = {
  title: 'Led Painting',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
