import '../styles/shared/global.css'
import QueryProvider from './lib/Providers'
import ReduxProvider from './redux/provider'


export const metadata = {
  title: 'Led Painting',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body>    
        <ReduxProvider>
          <QueryProvider>
              {children}  
          </QueryProvider>  
        </ReduxProvider>     
      </body>
    </html>
  )
}
